name: CI Demo Deploy

on:
  push:
    branches: [ master ]

env:
  GITHUB_DOCKER_REGISTRY: docker.pkg.github.com
  ORGANISATION: amadousanogo
  PROJECT: demo-cloud
  PACKAGE_NAME: dc-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install maven
        run: sudo apt install maven

      - name: Clean and create package
        run: sudo mvn clean package

      - name: Install docker
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install docker-ce
          sudo apt-mark hold docker-ce
          sudo systemctl status docker
          sudo usermod -aG docker $USER
      - name: Docker build
        run: |
          docker build -t $GITHUB_DOCKER_REGISTRY/$ORGANISATION/$PROJECT/$PACKAGE_NAME .
      - name: Docker login
        run: |
          docker login $GITHUB_DOCKER_REGISTRY -u ${{ secrets.USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: |
          docker push $GITHUB_DOCKER_REGISTRY/$ORGANISATION/$PROJECT/$PACKAGE_NAME
